<?php

/**
 * Services & Pricing Configuration
 *
 * Add, remove, or edit services here. Each service supports:
 * - name, price (INR), description, features[], duration, popular (bool)
 * - image: filename in public/images/services/ (optional — gradient placeholder used if missing)
 */

return [
    'bridal' => [
        [
            'name' => 'Bridal Trial',
            'image' => 'bridal-trial.jpg',
            'price' => 3500,
            'description' => 'Pre-wedding consultation and full face makeup trial',
            'features' => ['Pre-wedding consultation', 'Full face makeup trial', 'Look customization', 'Photo session'],
            'duration' => '2-3 hours',
            'popular' => false,
        ],
        [
            'name' => 'Full Bridal Makeup',
            'image' => 'full-bridal-makeup.jpg',
            'price' => 15000,
            'description' => 'Complete bridal look with long-lasting HD makeup',
            'features' => ['Complete bridal look', 'Long-lasting HD makeup', 'Premium products', 'Touch-up kit included', 'Photo-ready finish'],
            'duration' => '3-4 hours',
            'popular' => true,
        ],
        [
            'name' => 'Hair & Makeup Combo',
            'image' => 'hair-makeup-combo.jpg',
            'price' => 20000,
            'description' => 'Full bridal makeup with professional hair styling',
            'features' => ['Full bridal makeup', 'Professional hair styling', 'Hair accessories', 'Complete bridal look', 'Touch-up services'],
            'duration' => '4-5 hours',
            'popular' => false,
        ],
        [
            'name' => 'Bridal Party Makeup',
            'image' => 'bridal-party-makeup.jpg',
            'price' => 3500,
            'description' => 'Makeup for bridal party members (per person)',
            'features' => ['Per person pricing', 'Group discounts available', 'Coordinated looks', 'Professional finish'],
            'duration' => '1-2 hours',
            'popular' => false,
        ],
        [
            'name' => 'Engagement Makeup',
            'image' => 'engagement-makeup.jpg',
            'price' => 6000,
            'description' => 'Perfect look for your engagement photoshoot',
            'features' => ['Engagement photoshoot ready', 'Natural glam look', 'Long-lasting finish', 'Premium products'],
            'duration' => '2-3 hours',
            'popular' => false,
        ],
        [
            'name' => 'Mehendi Makeup',
            'image' => 'mehendi-makeup.jpg',
            'price' => 4500,
            'description' => 'Beautiful makeup for your mehendi ceremony',
            'features' => ['Traditional look', 'Long-lasting', 'Colorful design', 'Photo-ready'],
            'duration' => '2 hours',
            'popular' => false,
        ],
        [
            'name' => 'Reception Makeup',
            'image' => 'reception-makeup.jpg',
            'price' => 8000,
            'description' => 'Glamorous makeup for your reception party',
            'features' => ['Glamorous look', 'Evening appropriate', 'Long-lasting', 'Premium products'],
            'duration' => '2-3 hours',
            'popular' => false,
        ],
    ],
    'nails' => [
        [
            'name' => 'Classic Manicure',
            'image' => 'classic-manicure.jpg',
            'price' => 500,
            'description' => 'Traditional nail care and polish application',
            'features' => ['Nail shaping', 'Cuticle care', 'Hand massage', 'Polish application'],
            'duration' => '45 minutes',
            'popular' => false,
        ],
        [
            'name' => 'Gel Manicure',
            'image' => 'gel-manicure.jpg',
            'price' => 1200,
            'description' => 'Long-lasting gel polish manicure',
            'features' => ['Long-lasting gel polish', 'Up to 3 weeks wear', 'Chip-resistant', 'Shiny finish'],
            'duration' => '1 hour',
            'popular' => true,
        ],
        [
            'name' => 'Classic Pedicure',
            'image' => 'classic-pedicure.jpg',
            'price' => 700,
            'description' => 'Relaxing foot care and polish',
            'features' => ['Foot soak & scrub', 'Nail care', 'Foot massage', 'Polish application'],
            'duration' => '1 hour',
            'popular' => false,
        ],
        [
            'name' => 'Gel Pedicure',
            'image' => 'gel-pedicure.jpg',
            'price' => 1500,
            'description' => 'Long-lasting gel polish pedicure',
            'features' => ['Gel polish pedicure', 'Long-lasting finish', 'Complete foot care', 'Spa experience'],
            'duration' => '1.5 hours',
            'popular' => false,
        ],
        [
            'name' => 'Full Set (Manicure + Pedicure)',
            'image' => 'full-set-manicure-pedicure.jpg',
            'price' => 1800,
            'description' => 'Complete nail care package',
            'features' => ['Manicure + Pedicure', 'Complete nail care', 'Spa treatment', 'Polish of choice'],
            'duration' => '2 hours',
            'popular' => false,
        ],
        [
            'name' => 'Nail Art Design',
            'image' => 'nail-art-design.jpg',
            'price' => 500,
            'description' => 'Custom nail art designs (starting price)',
            'features' => ['Custom designs', 'Latest trends', 'Artistic patterns', 'Price varies by design'],
            'duration' => '30-60 minutes',
            'popular' => false,
        ],
        [
            'name' => 'French Manicure',
            'image' => 'french-manicure.jpg',
            'price' => 800,
            'description' => 'Classic French tip manicure',
            'features' => ['Classic French tips', 'Elegant look', 'Long-lasting', 'Professional finish'],
            'duration' => '1 hour',
            'popular' => false,
        ],
        [
            'name' => 'Spa Pedicure',
            'image' => 'spa-pedicure.jpg',
            'price' => 1800,
            'description' => 'Luxurious spa pedicure experience',
            'features' => ['Deep foot soak', 'Exfoliation', 'Foot massage', 'Moisturizing treatment', 'Polish'],
            'duration' => '1.5 hours',
            'popular' => false,
        ],
        [
            'name' => 'Nail Extension',
            'image' => 'nail-extension.jpg',
            'price' => 2500,
            'description' => 'Acrylic or gel nail extensions',
            'features' => ['Nail extensions', 'Custom length', 'Shape of choice', 'Polish included'],
            'duration' => '2-3 hours',
            'popular' => false,
        ],
    ],
    'beauty' => [
        [
            'name' => 'Full Face Makeup',
            'image' => 'full-face-makeup.jpg',
            'price' => 2500,
            'description' => 'Complete makeup application',
            'features' => ['Complete makeup', 'Contouring & highlighting', 'Eye makeup', 'Premium products'],
            'duration' => '1.5 hours',
            'popular' => false,
        ],
        [
            'name' => 'Party Makeup',
            'image' => 'party-makeup.jpg',
            'price' => 3000,
            'description' => 'Glamorous makeup for parties and events',
            'features' => ['Event-ready look', 'Long-lasting finish', 'Glamorous style', 'Photo-ready'],
            'duration' => '1.5 hours',
            'popular' => true,
        ],
        [
            'name' => 'Natural Makeup',
            'image' => 'natural-makeup.jpg',
            'price' => 2000,
            'description' => 'Subtle, natural-looking makeup',
            'features' => ['Natural look', 'Light coverage', 'Everyday style', 'Fresh appearance'],
            'duration' => '1 hour',
            'popular' => false,
        ],
        [
            'name' => 'Hair Styling',
            'image' => 'hair-styling.jpg',
            'price' => 1500,
            'description' => 'Professional hair styling for all occasions',
            'features' => ['Professional styling', 'All hair types', 'Long-lasting hold', 'Hair accessories'],
            'duration' => '1-2 hours',
            'popular' => false,
        ],
        [
            'name' => 'Eyebrow Threading',
            'image' => 'eyebrow-threading.jpg',
            'price' => 100,
            'description' => 'Precise eyebrow shaping',
            'features' => ['Precise shaping', 'Clean finish', 'Quick service', 'Professional technique'],
            'duration' => '15 minutes',
            'popular' => false,
        ],
        [
            'name' => 'Facial Treatment',
            'image' => 'facial-treatment.jpg',
            'price' => 2000,
            'description' => 'Rejuvenating facial therapy',
            'features' => ['Deep cleansing', 'Hydrating mask', 'Facial massage', 'Rejuvenating treatment'],
            'duration' => '1.5 hours',
            'popular' => false,
        ],
        [
            'name' => 'Hair Color',
            'image' => 'hair-color.jpg',
            'price' => 3500,
            'description' => 'Professional hair coloring service',
            'features' => ['Professional coloring', 'Color consultation', 'Premium products', 'Color protection'],
            'duration' => '3-4 hours',
            'popular' => false,
        ],
        [
            'name' => 'Haircut & Styling',
            'image' => 'haircut-styling.jpg',
            'price' => 800,
            'description' => 'Haircut with professional styling',
            'features' => ['Haircut', 'Professional styling', 'Consultation', 'Styling products'],
            'duration' => '1 hour',
            'popular' => false,
        ],
        [
            'name' => 'Hair Spa',
            'image' => 'hair-spa.jpg',
            'price' => 2500,
            'description' => 'Deep conditioning hair spa treatment',
            'features' => ['Deep conditioning', 'Hair massage', 'Scalp treatment', 'Smoothing treatment'],
            'duration' => '2 hours',
            'popular' => false,
        ],
        [
            'name' => 'Eyebrow Tinting',
            'image' => 'eyebrow-tinting.jpg',
            'price' => 500,
            'description' => 'Eyebrow color enhancement',
            'features' => ['Color enhancement', 'Natural look', 'Long-lasting', 'Quick service'],
            'duration' => '30 minutes',
            'popular' => false,
        ],
        [
            'name' => 'Eyelash Extension',
            'image' => 'eyelash-extension.jpg',
            'price' => 4000,
            'description' => 'Professional eyelash extensions',
            'features' => ['Full set extensions', 'Custom length', 'Natural look', 'Long-lasting'],
            'duration' => '2-3 hours',
            'popular' => false,
        ],
        [
            'name' => 'Makeup Consultation',
            'image' => 'makeup-consultation.jpg',
            'price' => 1000,
            'description' => 'Personalized makeup consultation',
            'features' => ['Color matching', 'Product recommendations', 'Technique tips', 'Personalized advice'],
            'duration' => '1 hour',
            'popular' => false,
        ],
    ],
];
